### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by katemalone**
Adds the userform and the create user form. I made them both the home router for access we will have to change that and the forms set state in store.

### CODE REVIEW

**Comment by ayladharamsey** [comment]
@katemalone Add a snapshot of your testing suite running here! Thank ya!

**Comment by ayladharamsey** [comment]
@katemalone Hey -- I just pulled this down and I'm now getting this error. Let me know when the application is up and running on this branch, and i'll look into merging it. Thanks! 
image

**Comment by ayladharamsey** [comment]
@katemalone looking over this now and I have a little more feedback: 

Route structure we determined last week: 
/ -- holds nav & movie container, prompts user to log in 
/ favorites -- holds user profile, nav, and favorites 
/ login -- our login form 
/ create-user -- create-user form 
/ movies -- movie container & nav & user profile 
/movies/:id -- movie information, user profile, & nav 

- We need the / route to route to the movie container with just movie data passed
- Currently at the / you have the CreateUser & Login User 
- I am unable to see the movies upon going to the site
- It looks like you have two things routing to /favorites, clarify what you would like to be routing that way. 
- I'm not sure whether or not user data is being set into the store— could you show me how that’s happening on the API side. Are you using Postgres to see that? There should be a table that you can confirm that users are making it into the database. 
- Run this through the existing test suite to ensure that it will not break other functionality within the application before pushing back up

**Comment by katemalone** [comment]
@ayladharamsey @mschneider247 
- The movie container error is an error on your end. I don't have it on my side. 
- the route were fixed CreateUser & Login User and 'sign in' button is going to movies container. 
- I was trying to ask you about two things being routed to favorites at union station and you told me it was fine. I also haven't touched those. Since you set up the routes I assumed you knew what was happening. 
- The user data is being set to the store. You can look in your redux dev tools to see the update of state.
as you can see below
Screen Shot 2019-10-26 at 2 43 11 PM
 
- Also when you try to create a user that has already been created its comes back as a server error. 
- if you'd like to see the stuff using postgres it's a bit complicated but you can set up postgres on your side and follow the directions they gave you in the setup instructions from the project repo. 

this is the link for the terminal commands to get to the database 
http://postgresguide.com/utilities/psql.html

Screen Shot 2019-10-26 at 2 27 01 PM

**Comment by ayladharamsey** [comment]
@katemalone Hey! So i just pulled down again and the routes are still a little disjointed. If you'd like to merge down master, branch off and just copy your css in so that you have our routes / functionality and add in that css that'd be awesome! Then we can break away from this branch and start on a clean slate.

**Pull request merged**
